### ISSUE TITLE
Matcher.matches not publically visiblie

### ISSUE THREAD

**Issue by potmo** [nschum/SwiftHamcrest#3]
I'm trying to do a mocking frameworks that extends the functionality of this project to also include things like `hasBeenCalledWithArg<ARG1, ARG2>(expectedArg1: Matcher<ARG1>, expectedArg2: Matcher<ARG2>)` but I can't since the `Matcher.matches` is in an internal scope. There seems to be a good function called `delegateMatching` in the `Hamcrest.swift` file but that one is also private. Could you please make at least one of them public?

**Comment by potmo** [comment]
Also `Matcher.description` would be helpful if I could access it

**Comment by nschum** [comment]
I've been conservative about what to make public, because I anticipated more changes as Swift evolves. :)
But you're right, `description` and `matches` should certainly be public.

`delegateMatching` is just an implementation detail, though. I'm not sure it'll stick around. If you want something similar, you should just copy it. :)
