### ISSUE TITLE
Warning in Xcode about 'HamcrestSwiftTestingMacros' Macro target

### ISSUE THREAD

**Issue by adil-hussain-84** [nschum/SwiftHamcrest#55]
I see the following warning in Xcode 16.2 when I upgrade my project to use this library's latest commit in the master branch:

```
/Users/adil/Library/Developer/Xcode/DerivedData/HifdhTracker-bnlnlnvnkzlewdepygzxsorxltff/SourcePackages/checkouts/SwiftHamcrest/SwiftTesting/Source/Macros/AssertThatMacro.swift Macro target 'HamcrestSwiftTestingMacros' must be enabled before it can be used in support of editor functionality
```

What is the 'HamcrestSwiftTestingMacros' Macro target and do I need to enable it to use this library? I'm reluctant to enable it because Xcode tells me "Macros with malicious code can harm your Mac or compromise your privacy. Be sure you trust the source of macros before you enable them."

**Comment by renep** [comment]
The macro adds compatibility with the new swift testing, by adding a new `#assertThat`macro, so that you can use the Hamcrest matchers with swift testing.
See: https://github.com/nschum/SwiftHamcrest?tab=readme-ov-file#swift-testing

The macros are in its own subproject, so it should be possible not to include this in your project. (But I have not tried it if the warning is then gone)

**Comment by adil-hussain-84** [comment]
Thanks for the response 🙏  I'm going to ignore the warning for now rather than trusting and enabling 'HamcrestSwiftTestingMacros'. I haven't found a way to disable 'HamcrestSwiftTestingMacros' and make the warning go away.
